name: build and test
run-name: ${{ github.actor }} run CI/CD
on: [push]
jobs:
  bazel-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: rules_prometheus
    - run: bazel build //... && bazel test //...
